Random Forest Algorithm is a supervised learning algorithm, that is the successsor the decision Table learning algorithm
Random forest is a machine learning algorithm that creates an ensemble of multiple decision trees to reach a singular, more accurate prediction or result.

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
# Load the dataset ---> we rae using customer chrun dataset for this example
data = pd.read_csv('D:\Python-Intro\ML\Datasets\chrun_dataset\WA_Fn-UseC_-Telco-Customer-Churn.csv')
data.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [5]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.1 MB

In [6]:
data.describe()

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [9]:
data.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='str')

In [10]:
data.tail()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [11]:
data.dtypes

customerID              str
gender                  str
SeniorCitizen         int64
Partner                 str
Dependents              str
tenure                int64
PhoneService            str
MultipleLines           str
InternetService         str
OnlineSecurity          str
OnlineBackup            str
DeviceProtection        str
TechSupport             str
StreamingTV             str
StreamingMovies         str
Contract                str
PaperlessBilling        str
PaymentMethod           str
MonthlyCharges      float64
TotalCharges            str
Churn                   str
dtype: object

In [12]:
data.shape

(7043, 21)

In [14]:
# Separte the features and target variable
X =data.drop('Churn', axis=1)
y=data['Churn']

In [18]:
# Drop the un-necessary columns from the dataset
X.drop(['customerID'], axis=1, inplace=True)

In [21]:
# Check the target variable distribution
print(y.value_counts())
print(y.value_counts(normalize=True))

Churn
No     5174
Yes    1869
Name: count, dtype: int64
Churn
No     0.73463
Yes    0.26537
Name: proportion, dtype: float64

In [28]:
# Map chrun data
y= data['Churn'].map({'Yes':1, 'No':0})

In [22]:
# Need to convert str to numeric value for TotalCharges column
X['TotalCharges'] = pd.to_numeric(X['TotalCharges'], errors='coerce')

In [23]:
data['TotalCharges'].isnull().sum()

np.int64(0)

In [25]:
# Now separate Numerical and categorical values form the dataset

# Separate Numerical columns
numerical_features = X.select_dtypes(include=[np.number])

# Separate Categorical columns (Use the built-in object, NOT np.object)
categorical_features = X.select_dtypes(include=[object])

C:\Users\user\AppData\Local\Temp\ipykernel_21276\1176093241.py:7: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_features = X.select_dtypes(include=[object])

In [27]:
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

In [29]:
# Create preprocessing pipelines for numerical and categorical features
numerical_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', StandardScaler())
])

categorical_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='constant', fill_value='missing')),
    ('onehot', OneHotEncoder(drop='first'))
])

preprocessor = ColumnTransformer([
    ('num', numerical_pipeline, numerical_features.columns),
    ('cat', categorical_pipeline, categorical_features.columns)
])

In [30]:
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [31]:
# create a random forest classifier
rf = RandomForestClassifier(n_estimators=100, random_state=42)

In [33]:
# combine preprocessor + Random Forest Classifier into a single pipeline
model = Pipeline([
    ("Pipeline", preprocessor),
    ("RandomForest", rf)
])

In [35]:
model.fit(X_train,y_train)

Pipeline(steps=[('Pipeline',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  Index(['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges'], dtype='str')),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(fill_value='missing',
                                                                                 strategy='constant')),
                                                                  ('onehot',
                                                                   OneHotEncoder(drop='first'))]),
                                                  Index(['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines',
       'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
       'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract',
       'PaperlessBilling', 'PaymentMethod'],
      dtype='str'))])),
                ('RandomForest', RandomForestClassifier(random_state=42))])

In [36]:
y_pred = model.predict(X_test)

In [42]:
accuracy = accuracy_score(y_test, y_pred)
print(accuracy)

0.7927608232789212

In [43]:
precision = precision_score(y_test, y_pred)
print(precision)

0.651685393258427

In [44]:
recall = recall_score(y_test, y_pred)
print(recall)

0.46648793565683644

In [45]:
f1_score = f1_score(y_test, y_pred)
print(f1_score)

0.54375

In [46]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.83      0.91      0.87      1036
           1       0.65      0.47      0.54       373

    accuracy                           0.79      1409
   macro avg       0.74      0.69      0.70      1409
weighted avg       0.78      0.79      0.78      1409

In [47]:
# confusion matrix
cnf = confusion_matrix(y_test, y_pred)
print(cnf)

[[943  93]
 [199 174]]

In [56]:
#  FIXED: Added the pipeline step prefix 'RandomForest__' to every parameter
param_distributions = {
    'RandomForest__n_estimators':[50,100,150,200],
    'RandomForest__max_depth': [None, 10, 20],
    'RandomForest__min_samples_leaf': [1, 2, 4],
    'RandomForest__min_samples_split': [2, 5, 10],
    'RandomForest__max_features': ['auto', 'sqrt', 'log2'],
    'RandomForest__class_weight': ['balanced', 'balanced_subsample', None]
}

In [57]:
# RandomizedSearchCV for hyperparameter tuning
from sklearn.model_selection import RandomizedSearchCV

In [58]:
random_search = RandomizedSearchCV(
    estimator=model,
    param_distributions=param_distributions,
    n_iter =30,
    cv=5,
    scoring='f1',
    random_state=42,
    n_jobs=-1,
    verbose=2
)

In [59]:
random_search.fit(X_train, y_train)

Fitting 5 folds for each of 30 candidates, totalling 150 fits

c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_validation.py:493: FitFailedWarning:
35 fits failed out of a total of 150.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
19 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_validation.py", line 855, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py", line 1403, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\pipeline.py", line 645, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py", line 1393, in wrapper
    estimator._validate_params()
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py", line 554, in _validate_params
    validate_parameter_constraints(
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
16 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_validation.py", line 855, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py", line 1403, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\pipeline.py", line 645, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py", line 1393, in wrapper
    estimator._validate_params()
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py", line 554, in _validate_params
    validate_parameter_constraints(
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_search.py:1237: UserWarning: One or more of the test scores are non-finite: [       nan 0.62905546 0.56655657 0.62586141 0.62588866 0.62797126
 0.62374234 0.62156239 0.56562498        nan        nan        nan
 0.56441838 0.62595407 0.5715615  0.60896343 0.53718986        nan
 0.56606345 0.61967176 0.62729325 0.62571176 0.62975664 0.62106737
 0.62015206 0.63027192        nan 0.61637111        nan 0.57119231]
  warnings.warn(

RandomizedSearchCV(cv=5,
                   estimator=Pipeline(steps=[('Pipeline',
                                              ColumnTransformer(transformers=[('num',
                                                                               Pipeline(steps=[('imputer',
                                                                                                SimpleImputer()),
                                                                                               ('scaler',
                                                                                                StandardScaler())]),
                                                                               Index(['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges'], dtype='str')),
                                                                              ('cat',
                                                                               Pipeline(steps=[('imputer',
                                                                                                SimpleImputer(fill_value='missing',
                                                                                                              strategy='constant')),
                                                                                               ('one...
                   param_distributions={'RandomForest__class_weight': ['balanced',
                                                                       'balanced_subsample',
                                                                       None],
                                        'RandomForest__max_depth': [None, 10,
                                                                    20],
                                        'RandomForest__max_features': ['auto',
                                                                       'sqrt',
                                                                       'log2'],
                                        'RandomForest__min_samples_leaf': [1, 2,
                                                                           4],
                                        'RandomForest__min_samples_split': [2,
                                                                            5,
                                                                            10],
                                        'RandomForest__n_estimators': [50, 100,
                                                                       150,
                                                                       200]},
                   random_state=42, scoring='f1', verbose=2)

In [60]:
random_search.best_score_

np.float64(0.6302719228929123)

In [61]:
best_model = random_search.best_estimator_

In [62]:
y_pred = best_model.predict(X_test)

In [63]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.92      0.76      0.84      1036
           1       0.56      0.82      0.66       373

    accuracy                           0.78      1409
   macro avg       0.74      0.79      0.75      1409
weighted avg       0.83      0.78      0.79      1409

In [64]:
# inspect all 30 experiments and their results
results_df = pd.DataFrame(random_search.cv_results_)

In [68]:
print(results_df)

    mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0        0.498796      0.051471         0.000000        0.000000
1        5.045577      1.204227         0.261613        0.040847
2        3.856204      0.591439         0.258760        0.037336
3        2.643972      0.307268         0.156494        0.031455
4        1.404900      0.215781         0.127003        0.012686
5        4.950249      1.146463         0.228528        0.015711
6        2.326458      0.264468         0.158658        0.010940
7        1.209701      0.220413         0.109343        0.004494
8        3.175291      0.161077         0.223184        0.013701
9        0.192866      0.031756         0.000000        0.000000
10       0.176759      0.015490         0.000000        0.000000
11       0.136764      0.010684         0.000000        0.000000
12       0.850982      0.042338         0.104418        0.008210
13       3.007228      0.401705         0.170850        0.007712
14       2.827593      0.476174         0.201730        0.045107
15       4.436253      0.534387         0.236842        0.022544
16       1.318877      0.059198         0.133107        0.016192
17       0.204669      0.028046         0.000000        0.000000
18       1.680508      0.094463         0.149795        0.012569
19       3.713734      0.318846         0.242747        0.013654
20       2.663683      0.211320         0.190211        0.022959
21       1.935573      0.134360         0.149503        0.006762
22       1.082234      0.086636         0.105374        0.002153
23       2.904471      0.280557         0.196605        0.010297
24       3.871434      0.243412         0.216755        0.008145
25       2.840670      0.142201         0.189843        0.021479
26       0.232352      0.043140         0.000000        0.000000
27       1.097540      0.072032         0.108565        0.011426
28       0.143748      0.032627         0.000000        0.000000
29       4.955212      0.465447         0.297917        0.077621

    param_RandomForest__n_estimators  param_RandomForest__min_samples_split  \
0                                200                                     10
1                                150                                     10
2                                200                                      2
3                                100                                      5
4                                 50                                     10
5                                200                                      5
6                                100                                      2
7                                 50                                      5
8                                200                                      5
9                                100                                      2
10                               150                                      2
11                               200                                      2
12                                50                                     10
13                               150                                     10
14                               150                                      5
15                               200                                      2
16                                50                                      2
17                               150                                      5
18                               100                                     10
19                               200                                      5
20                               150                                      5
21                               100                                     10
22                                50                                      2
23                               150                                      5
24                               200                                     10
25                               150                                      5
26                                50                                      5
27                                50                                      5
28                               200                                     10
29                               200                                     10

    param_RandomForest__min_samples_leaf param_RandomForest__max_features  \
0                                      1                             auto
1                                      4                             sqrt
2                                      4                             log2
3                                      2                             sqrt
4                                      4                             log2
5                                      4                             log2
6                                      4                             sqrt
7                                      4                             sqrt
8                                      4                             log2
9                                      4                             auto
10                                     2                             auto
11                                     1                             auto
12                                     1                             sqrt
13                                     1                             sqrt
14                                     4                             sqrt
15                                     2                             log2
16                                     1                             log2
17                                     4                             auto
18                                     1                             sqrt
19                                     2                             log2
20                                     4                             log2
21                                     2                             log2
22                                     4                             sqrt
23                                     1                             log2
24                                     2                             sqrt
25                                     2                             log2
26                                     4                             auto
27                                     1                             log2
28                                     2                             auto
29                                     4                             log2

   param_RandomForest__max_depth param_RandomForest__class_weight  \
0                             10                              NaN
1                           None                         balanced
2                             10                              NaN
3                             10               balanced_subsample
4                             20               balanced_subsample
5                             10               balanced_subsample
6                             20                         balanced
7                             20                         balanced
8                             20                              NaN
9                             20                              NaN
10                            20               balanced_subsample
11                            20                              NaN
12                            10                              NaN
13                            10               balanced_subsample
14                          None                              NaN
15                          None               balanced_subsample
16                          None                              NaN
17                          None                         balanced
18                            10                              NaN
19                            20                         balanced
20                            10                         balanced
21                            20                         balanced
22                            10                         balanced
23                            20                         balanced
24                          None                         balanced
25                            10                         balanced
26                          None               balanced_subsample
27                          None                         balanced
28                          None                         balanced
29                          None                              NaN

                                               params  split0_test_score  \
0   {'RandomForest__n_estimators': 200, 'RandomFor...                NaN
1   {'RandomForest__n_estimators': 150, 'RandomFor...           0.663073
2   {'RandomForest__n_estimators': 200, 'RandomFor...           0.610487
3   {'RandomForest__n_estimators': 100, 'RandomFor...           0.639118
4   {'RandomForest__n_estimators': 50, 'RandomFore...           0.649789
5   {'RandomForest__n_estimators': 200, 'RandomFor...           0.653846
6   {'RandomForest__n_estimators': 100, 'RandomFor...           0.647773
7   {'RandomForest__n_estimators': 50, 'RandomFore...           0.652233
8   {'RandomForest__n_estimators': 200, 'RandomFor...           0.615672
9   {'RandomForest__n_estimators': 100, 'RandomFor...                NaN
10  {'RandomForest__n_estimators': 150, 'RandomFor...                NaN
11  {'RandomForest__n_estimators': 200, 'RandomFor...                NaN
12  {'RandomForest__n_estimators': 50, 'RandomFore...           0.608379
13  {'RandomForest__n_estimators': 150, 'RandomFor...           0.650069
14  {'RandomForest__n_estimators': 150, 'RandomFor...           0.615101
15  {'RandomForest__n_estimators': 200, 'RandomFor...           0.631902
16  {'RandomForest__n_estimators': 50, 'RandomFore...           0.587800
17  {'RandomForest__n_estimators': 150, 'RandomFor...                NaN
18  {'RandomForest__n_estimators': 100, 'RandomFor...           0.603291
19  {'RandomForest__n_estimators': 200, 'RandomFor...           0.640669
20  {'RandomForest__n_estimators': 150, 'RandomFor...           0.654305
21  {'RandomForest__n_estimators': 100, 'RandomFor...           0.649315
22  {'RandomForest__n_estimators': 50, 'RandomFore...           0.654305
23  {'RandomForest__n_estimators': 150, 'RandomFor...           0.639653
24  {'RandomForest__n_estimators': 200, 'RandomFor...           0.647619
25  {'RandomForest__n_estimators': 150, 'RandomFor...           0.656915
26  {'RandomForest__n_estimators': 50, 'RandomFore...                NaN
27  {'RandomForest__n_estimators': 50, 'RandomFore...           0.631884
28  {'RandomForest__n_estimators': 200, 'RandomFor...                NaN
29  {'RandomForest__n_estimators': 200, 'RandomFor...           0.612782

    split1_test_score  split2_test_score  split3_test_score  \
0                 NaN                NaN                NaN
1            0.618911           0.611732           0.629275
2            0.575397           0.553435           0.562852
3            0.635821           0.611354           0.616690
4            0.632987           0.600871           0.644886
5            0.626996           0.617354           0.624484
6            0.623044           0.617772           0.618529
7            0.616046           0.611732           0.617486
8            0.568588           0.542308           0.564972
9                 NaN                NaN                NaN
10                NaN                NaN                NaN
11                NaN                NaN                NaN
12           0.568093           0.536585           0.575701
13           0.627393           0.609827           0.622721
14           0.574257           0.552783           0.565465
15           0.634711           0.598400           0.600000
16           0.539683           0.485549           0.544762
17                NaN                NaN                NaN
18           0.574803           0.533835           0.583178
19           0.630814           0.607558           0.619318
20           0.620499           0.617931           0.619423
21           0.631124           0.612994           0.622222
22           0.633941           0.617080           0.617251
23           0.634294           0.610370           0.619469
24           0.633238           0.606838           0.609179
25           0.631579           0.615172           0.622517
26                NaN                NaN                NaN
27           0.633028           0.606876           0.609467
28                NaN                NaN                NaN
29           0.579365           0.557252           0.564394

    split4_test_score  mean_test_score  std_test_score  rank_test_score
0                 NaN              NaN             NaN               24
1            0.622287         0.629055        0.017922                3
2            0.530612         0.566557        0.026404               19
3            0.626324         0.625861        0.010675                8
4            0.600910         0.625889        0.021130                7
5            0.617176         0.627971        0.013505                4
6            0.611594         0.623742        0.012557               10
7            0.610315         0.621562        0.015562               11
8            0.536585         0.565625        0.027932               21
9                 NaN              NaN             NaN               24
10                NaN              NaN             NaN               24
11                NaN              NaN             NaN               24
12           0.533333         0.564418        0.027620               22
13           0.619760         0.625954        0.013361                6
14           0.550201         0.571562        0.023448               17
15           0.579805         0.608963        0.021125               16
16           0.528155         0.537190        0.032782               23
17                NaN              NaN             NaN               24
18           0.535211         0.566063        0.027370               20
19           0.600000         0.619672        0.014825               14
20           0.624309         0.627293        0.013670                5
21           0.612903         0.625712        0.013597                9
22           0.626207         0.629757        0.013783                2
23           0.601550         0.621067        0.014271               12
24           0.603886         0.620152        0.017251               13
25           0.625177         0.630272        0.014322                1
26                NaN              NaN             NaN               24
27           0.600601         0.616371        0.013451               15
28                NaN              NaN             NaN               24
29           0.542169         0.571192        0.023998               18